import localFont from "next/font/local";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-r from-cyan-500 to-blue-500"
      >
        {children}
      </body>
    </html>
  );
}